### ISSUE TITLE
what happened to simple.py?

### ISSUE THREAD

**Issue by deatonjm** [megwill4268/mission_to_mars#1]
Did it get moved? I was going to start borrowing that code for my examples :)

**Comment by megwill4268** [comment]
Hi, it got moved to  https://github.com/megwill4268/mission_to_mars_tutorial as the mission to mars became the challenge for the hackathon and didn't makesense here.

**Comment by deatonjm** [comment]
ahhh right! sorry, i didn't watch that space so I couldn't see it. The other issue I opened really belongs in that space. i'll move it :)
